### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by akadiryazici** [JPNaude/Qtilities#59]
hi everyone,
I am trying to build qtilities on windows xp environment to use dynamicpropertybrowser. I downloaded the source file and opened it in QtCreator with Qt SDK 4.8. While building the project, I am getting undeclared identifier errors for Itask. there are some other compile time errors as well. I was wondering if there is someone who built qtilities on windows before. What are the basic steps to compile minimal qtilities project? I read the building instructions but could not find anything useful to solve my problem. 

thanks.

**Comment by davidmulihase** [comment]
I cant build the project on Ubuntu 18.04
